// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./src/components/syntax/A.vue')['default']
    AccessingProps: typeof import('./src/components/syntax/AccessingProps.vue')['default']
    AddLine: typeof import('./src/components/AddLine.vue')['default']
    AntVX6: typeof import('./src/components/demo/AntVX6.vue')['default']
    Attr: typeof import('./src/components/html/Attr.vue')['default']
    B: typeof import('./src/components/syntax/B.vue')['default']
    BuiltIns: typeof import('./src/components/syntax/BuiltIns.vue')['default']
    Child: typeof import('./src/components/Child.vue')['default']
    ClassDemo: typeof import('./src/components/ClassDemo.vue')['default']
    ColoredIcon: typeof import('./src/components/demo/ColoredIcon.vue')['default']
    ColorIcon: typeof import('./src/components/demo/ColorIcon.vue')['default']
    ColorIconDemo: typeof import('./src/components/demo/ColorIconDemo.vue')['default']
    ComputedTest: typeof import('./src/components/syntax/ComputedTest.vue')['default']
    ComputedWatch: typeof import('./src/components/syntax/ComputedWatch.vue')['default']
    DatePickerDemo: typeof import('./src/components/element/DatePickerDemo.vue')['default']
    DayjsDemo: typeof import('./src/components/demo/DayjsDemo.vue')['default']
    Demo: typeof import('./src/components/Demo.vue')['default']
    Dog: typeof import('./src/components/Dog.vue')['default']
    DraggableDemo: typeof import('./src/components/DraggableDemo.vue')['default']
    DraggableDemo1: typeof import('./src/components/DraggableDemo1.vue')['default']
    ElementDemo: typeof import('./src/components/element/ElementDemo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HTMLSandbox: typeof import('./src/components/html/HTMLSandbox.vue')['default']
    IconDemo: typeof import('./src/components/demo/IconDemo.vue')['default']
    IDBDemo: typeof import('./src/components/IDBDemo.vue')['default']
    KeepAliveDemo: typeof import('./src/components/syntax/KeepAliveDemo.vue')['default']
    Leaf: typeof import('./src/components/demo/Leaf.vue')['default']
    Modifiers: typeof import('./src/components/syntax/Modifiers.vue')['default']
    OrgStructure: typeof import('./src/components/demo/OrgStructure.vue')['default']
    Parent: typeof import('./src/components/Parent.vue')['default']
    PiniaDemo: typeof import('./src/components/demo/PiniaDemo.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    PropsTest: typeof import('./src/components/syntax/PropsTest.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    SwitchDemo: typeof import('./src/components/element/SwitchDemo.vue')['default']
    Tree: typeof import('./src/components/demo/Tree.vue')['default']
    VueSyntax: typeof import('./src/components/syntax/VueSyntax.vue')['default']
    VueTourDemo: typeof import('./src/components/demo/VueTourDemo.vue')['default']
    VuexDemo: typeof import('./src/components/VuexDemo.vue')['default']
    VuexDemo1: typeof import('./src/components/VuexDemo1.vue')['default']
  }
}

export { }
